import React from 'react';
import { StyleSheet, ScrollView, TouchableOpacity, Linking } from 'react-native';
import { useRouter } from 'expo-router';
import { ThemedText } from '@/components/ThemedText';
import { ThemedView } from '@/components/ThemedView';

export default function AboutScreen() {
    const router = useRouter();

    const handleContactPress = () => {
        Linking.openURL('mailto:morrisonyuriandrei2@gmail.com');
    };

    return (
        <ScrollView style={styles.container}>
            {/* Back Button */}
            <ThemedView style={styles.backButtonContainer}>
                <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
                    <ThemedText style={styles.backButtonText}>← Back</ThemedText>
                </TouchableOpacity>
            </ThemedView>

            {/* Header */}
            <ThemedView style={styles.headerSection}>
                <ThemedText type="title" style={styles.appTitle}>Waste to Worth</ThemedText>
                <ThemedText style={styles.tagline}>Transforming waste into valuable resources</ThemedText>
                <ThemedText style={styles.version}>Version 1.0.0</ThemedText>
            </ThemedView>

            {/* Mission Section */}
            <ThemedView style={styles.section}>
                <ThemedText type="subtitle" style={styles.sectionTitle}>Our Mission</ThemedText>
                <ThemedText style={styles.sectionText}>
                    Waste to Worth is dedicated to reducing environmental waste by helping users discover 
                    creative and practical ways to upcycle their everyday items. We believe that with a 
                    little creativity and guidance, almost anything can be transformed into something 
                    useful and beautiful.
                </ThemedText>
            </ThemedView>

            {/* Features Section */}
            <ThemedView style={styles.section}>
                <ThemedText type="subtitle" style={styles.sectionTitle}>Key Features</ThemedText>
                
                <ThemedView style={styles.featureItem}>
                    <ThemedText style={styles.featureTitle}>📱 Smart Material Recognition</ThemedText>
                    <ThemedText style={styles.featureText}>
                        Use your camera to identify materials and get instant recycling suggestions.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={styles.featureTitle}>🎨 AI-Powered Project Ideas</ThemedText>
                    <ThemedText style={styles.featureText}>
                        Get personalized upcycling project ideas generated by advanced AI technology.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={styles.featureTitle}>📚 Step-by-Step Instructions</ThemedText>
                    <ThemedText style={styles.featureText}>
                        Follow detailed, easy-to-understand instructions for every project.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={styles.featureTitle}>📊 Progress Tracking</ThemedText>
                    <ThemedText style={styles.featureText}>
                        Track your recycling journey and see the positive impact you're making.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={styles.featureTitle}>👥 Community Sharing</ThemedText>
                    <ThemedText style={styles.featureText}>
                        Share your creations and get inspired by others in the community.
                    </ThemedText>
                </ThemedView>
            </ThemedView>

            {/* Technology Section */}
            <ThemedView style={styles.section}>
                <ThemedText type="subtitle" style={styles.sectionTitle}>Technology</ThemedText>
                <ThemedText style={styles.sectionText}>
                    Waste to Worth is powered by cutting-edge technology including:
                </ThemedText>
                
                <ThemedView style={styles.techItem}>
                    <ThemedText style={styles.techTitle}>• Google Gemini AI</ThemedText>
                    <ThemedText style={styles.techText}>For intelligent project generation and material analysis</ThemedText>
                </ThemedView>

                <ThemedView style={styles.techItem}>
                    <ThemedText style={styles.techTitle}>• Firebase</ThemedText>
                    <ThemedText style={styles.techText}>For secure data storage and real-time synchronization</ThemedText>
                </ThemedView>

                <ThemedView style={styles.techItem}>
                    <ThemedText style={styles.techTitle}>• React Native & Expo</ThemedText>
                    <ThemedText style={styles.techText}>For cross-platform mobile app development</ThemedText>
                </ThemedView>

                <ThemedView style={styles.techItem}>
                    <ThemedText style={styles.techTitle}>• Flask Backend</ThemedText>
                    <ThemedText style={styles.techText}>For robust API services and data processing</ThemedText>
                </ThemedView>
            </ThemedView>

            {/* Impact Section */}
            <ThemedView style={styles.section}>
                <ThemedText type="subtitle" style={styles.sectionTitle}>Environmental Impact</ThemedText>
                <ThemedText style={styles.sectionText}>
                    Every upcycling project you complete helps reduce waste and contributes to a more 
                    sustainable future. Together, we can make a significant difference in protecting 
                    our planet for future generations.
                </ThemedText>
            </ThemedView>

            {/* Contact Section */}
            <ThemedView style={styles.section}>
                <ThemedText type="subtitle" style={styles.sectionTitle}>Get in Touch</ThemedText>
                <ThemedText style={styles.sectionText}>
                    Have questions, suggestions, or want to share your success stories? We'd love to hear from you!
                </ThemedText>
                
                <TouchableOpacity style={styles.contactButton} onPress={handleContactPress}>
                    <ThemedText style={styles.contactButtonText}>📧 Contact Support</ThemedText>
                </TouchableOpacity>

            </ThemedView>

            {/* Footer */}
            <ThemedView style={styles.footerSection}>
                <ThemedText style={styles.footerText}>
                    © 2025 Waste to Worth. All rights reserved.
                </ThemedText>
                <ThemedText style={styles.footerText}>
                    Made with ❤️ for a sustainable future
                </ThemedText>
            </ThemedView>
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    backButtonContainer: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 8,
    },
    backButton: {
        alignSelf: 'flex-start',
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: '#f0f0f0',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ddd',
    },
    backButtonText: {
        color: '#007AFF',
        fontSize: 16,
        fontWeight: '500',
    },
    headerSection: {
        backgroundColor: '#fff',
        padding: 24,
        marginHorizontal: 16,
        marginBottom: 16,
        borderRadius: 12,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    appTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#2c3e50',
        marginBottom: 8,
    },
    tagline: {
        fontSize: 16,
        color: '#7f8c8d',
        textAlign: 'center',
        marginBottom: 8,
        fontStyle: 'italic',
    },
    version: {
        fontSize: 14,
        color: '#95a5a6',
        fontWeight: '500',
    },
    section: {
        backgroundColor: '#fff',
        padding: 20,
        marginHorizontal: 16,
        marginBottom: 16,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2c3e50',
        marginBottom: 16,
    },
    sectionText: {
        fontSize: 16,
        lineHeight: 24,
        color: '#34495e',
        marginBottom: 16,
    },
    featureItem: {
        marginBottom: 16,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#ecf0f1',
    },
    featureTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2c3e50',
        marginBottom: 8,
    },
    featureText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#7f8c8d',
    },
    techItem: {
        marginBottom: 12,
    },
    techTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2c3e50',
        marginBottom: 4,
    },
    techText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#7f8c8d',
        marginLeft: 16,
    },
    contactButton: {
        backgroundColor: '#3498db',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        marginBottom: 12,
        alignItems: 'center',
    },
    contactButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    websiteButton: {
        backgroundColor: '#27ae60',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
    },
    websiteButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    footerSection: {
        backgroundColor: '#34495e',
        padding: 20,
        marginHorizontal: 16,
        marginBottom: 32,
        borderRadius: 12,
        alignItems: 'center',
    },
    footerText: {
        color: '#ecf0f1',
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 4,
    },
});
