import React from 'react';
import { StyleSheet, ScrollView, TouchableOpacity, Linking, View, Platform, Pressable } from 'react-native';
import { useRouter } from 'expo-router';
import { ThemedText } from '@/components/ThemedText';
import { ThemedView } from '@/components/ThemedView';
import { AuthGuard } from '@/components/AuthGuard';
import { Colors } from '@/constants/Colors';
import { Image } from 'expo-image';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';

function AboutScreen() {
    const router = useRouter();

    const handleBack = () => {
        router.back();
    };

    const handleContactPress = () => {
        Linking.openURL('mailto:morrisonyuriandrei2@gmail.com');
    };

    return (
        <ThemedView style={[styles.container, { backgroundColor: Colors.background }]}>
            {/* Header */}
            <ThemedView style={styles.header}>
                <Pressable onPress={handleBack} style={styles.backButton}>
                    <MaterialIcons name="arrow-back" size={24} color={Colors.text} />
                </Pressable>
                <ThemedText type="title" style={styles.headerTitle}>About</ThemedText>
                <View style={styles.placeholder} />
            </ThemedView>

            <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>

                {/* App Header with Logo */}
                <ThemedView style={styles.headerSection}>
                    <Image
                        source={require('@/assets/images/logo animation 3.png')}
                        style={styles.logo}
                        resizeMode="contain"
                    />
                    <ThemedText type="title" style={styles.appTitle}>Waste to Worth</ThemedText>
                    <ThemedText style={styles.tagline}>Transforming waste into valuable resources</ThemedText>
                    <ThemedText style={styles.version}>Version 1.0.0</ThemedText>
                </ThemedView>

            {/* Mission Section */}
            <ThemedView style={styles.section}>
                <ThemedText type="subtitle" style={styles.sectionTitle}>Our Mission</ThemedText>
                <ThemedText style={styles.sectionText}>
                    Waste to Worth is dedicated to reducing environmental waste by helping users discover 
                    creative and practical ways to upcycle their everyday items. We believe that with a 
                    little creativity and guidance, almost anything can be transformed into something 
                    useful and beautiful.
                </ThemedText>
            </ThemedView>

            {/* Features Section */}
            <ThemedView style={styles.section}>
                <ThemedText type="subtitle" style={styles.sectionTitle}>Key Features</ThemedText>
                
                <ThemedView style={styles.featureItem}>
                    <ThemedText style={styles.featureTitle}>📱 Smart Material Recognition</ThemedText>
                    <ThemedText style={styles.featureText}>
                        Use your camera to identify materials and get instant recycling suggestions.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={styles.featureTitle}>🎨 AI-Powered Project Ideas</ThemedText>
                    <ThemedText style={styles.featureText}>
                        Get personalized upcycling project ideas generated by advanced AI technology.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={styles.featureTitle}>📚 Step-by-Step Instructions</ThemedText>
                    <ThemedText style={styles.featureText}>
                        Follow detailed, easy-to-understand instructions for every project.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={styles.featureTitle}>📊 Progress Tracking</ThemedText>
                    <ThemedText style={styles.featureText}>
                        Track your recycling journey and see the positive impact you're making.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={styles.featureTitle}>👥 Community Sharing</ThemedText>
                    <ThemedText style={styles.featureText}>
                        Share your creations and get inspired by others in the community.
                    </ThemedText>
                </ThemedView>
            </ThemedView>

            {/* Technology Section */}
            <ThemedView style={styles.section}>
                <ThemedText type="subtitle" style={styles.sectionTitle}>Technology</ThemedText>
                <ThemedText style={styles.sectionText}>
                    Waste to Worth is powered by cutting-edge technology including:
                </ThemedText>
                
                <ThemedView style={styles.techItem}>
                    <ThemedText style={styles.techTitle}>• Google Gemini AI</ThemedText>
                    <ThemedText style={styles.techText}>For intelligent project generation and material analysis</ThemedText>
                </ThemedView>

                <ThemedView style={styles.techItem}>
                    <ThemedText style={styles.techTitle}>• Firebase</ThemedText>
                    <ThemedText style={styles.techText}>For secure data storage and real-time synchronization</ThemedText>
                </ThemedView>

                <ThemedView style={styles.techItem}>
                    <ThemedText style={styles.techTitle}>• React Native & Expo</ThemedText>
                    <ThemedText style={styles.techText}>For cross-platform mobile app development</ThemedText>
                </ThemedView>

                <ThemedView style={styles.techItem}>
                    <ThemedText style={styles.techTitle}>• Flask Backend</ThemedText>
                    <ThemedText style={styles.techText}>For robust API services and data processing</ThemedText>
                </ThemedView>
            </ThemedView>

            {/* Impact Section */}
            <ThemedView style={styles.section}>
                <ThemedText type="subtitle" style={styles.sectionTitle}>Environmental Impact</ThemedText>
                <ThemedText style={styles.sectionText}>
                    Every upcycling project you complete helps reduce waste and contributes to a more 
                    sustainable future. Together, we can make a significant difference in protecting 
                    our planet for future generations.
                </ThemedText>
            </ThemedView>

            {/* Contact Section */}
            <ThemedView style={styles.section}>
                <ThemedText type="subtitle" style={styles.sectionTitle}>Get in Touch</ThemedText>
                <ThemedText style={styles.sectionText}>
                    Have questions, suggestions, or want to share your success stories? We'd love to hear from you!
                </ThemedText>
                
                <TouchableOpacity style={styles.contactButton} onPress={handleContactPress}>
                    <ThemedText style={styles.contactButtonText}>📧 Contact Support</ThemedText>
                </TouchableOpacity>
            </ThemedView>

            </ScrollView>
        </ThemedView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 50,
        paddingBottom: 20,
        backgroundColor: Platform.OS === 'web' ? 'rgba(255, 255, 255, 0.6)' : 'rgba(255, 255, 255, 0.7)',
        borderBottomWidth: 1,
        borderBottomColor: '#00630F',
        ...(Platform.OS === 'web' && { backdropFilter: 'blur(10px)' }),
    },
    backButton: {
        padding: 8,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    placeholder: {
        width: 40,
    },
    content: {
        flex: 1,
        padding: 20,
    },
    headerSection: {
        backgroundColor: Platform.OS === 'web' ? 'rgba(255, 255, 255, 0.6)' : 'rgba(255, 255, 255, 0.7)',
        padding: 24,
        marginBottom: 20,
        borderRadius: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        ...(Platform.OS === 'web' && { backdropFilter: 'blur(10px)' }),
    },
    logo: {
        width: 120,
        height: 120,
        marginBottom: 16,
    },
    appTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#00630F',
        marginBottom: 8,
    },
    tagline: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        marginBottom: 8,
        fontStyle: 'italic',
    },
    version: {
        fontSize: 14,
        color: '#888',
        fontWeight: '500',
    },
    section: {
        backgroundColor: '#FFFFFF',
        padding: 20,
        marginBottom: 20,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#00630F',
        marginBottom: 16,
    },
    sectionText: {
        fontSize: 16,
        lineHeight: 24,
        color: '#34495e',
        marginBottom: 16,
    },
    featureItem: {
        marginBottom: 16,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#ecf0f1',
    },
    featureTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2c3e50',
        marginBottom: 8,
    },
    featureText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#7f8c8d',
    },
    techItem: {
        marginBottom: 12,
    },
    techTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2c3e50',
        marginBottom: 4,
    },
    techText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#7f8c8d',
        marginLeft: 16,
    },
    contactButton: {
        backgroundColor: '#00630F',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 20,
        marginBottom: 12,
        alignItems: 'center',
    },
    contactButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    websiteButton: {
        backgroundColor: '#27ae60',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
    },
    websiteButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
});

export default function AboutScreenWithAuth() {
    return (
        <AuthGuard>
            <AboutScreen />
        </AuthGuard>
    );
}
