import React from 'react';
import { StyleSheet, ScrollView, TouchableOpacity, Linking } from 'react-native';
import { useRouter } from 'expo-router';
import { ThemedText } from '@/components/ThemedText';
import { ThemedView } from '@/components/ThemedView';
import { usePalette } from '@/hooks/usePalette';
import { Radii, Spacing, Shadows } from '@/constants/DesignTokens';

export default function AboutScreen() {
    const router = useRouter();
    const P = usePalette();

    const handleContactPress = () => {
        Linking.openURL('mailto:morrisonyuriandrei2@gmail.com');
    };

    return (
        <ScrollView style={[styles.container, { backgroundColor: P.background }]}>
            {/* Back Button */}
            <ThemedView style={[styles.backButtonContainer]}>
                <TouchableOpacity style={[styles.backButton, { backgroundColor: P.backgroundSecondary, borderColor: P.border, borderRadius: Radii.lg }]} onPress={() => router.back()}>
                    <ThemedText style={styles.backButtonText}>← Back</ThemedText>
                </TouchableOpacity>
            </ThemedView>

            {/* Header */}
            <ThemedView style={[styles.headerSection, { backgroundColor: P.card, borderRadius: Radii.md, ...(Shadows.soft as any) }]}>
                <ThemedText type="title" style={[styles.appTitle, { color: P.text }]}>Waste to Worth</ThemedText>
                <ThemedText style={[styles.tagline, { color: P.text + '99' }]}>Transforming waste into valuable resources</ThemedText>
                <ThemedText style={[styles.version, { color: P.text + '80' }]}>Version 1.0.0</ThemedText>
            </ThemedView>

            {/* Mission Section */}
            <ThemedView style={[styles.section, { backgroundColor: P.card, borderRadius: Radii.md, ...(Shadows.soft as any) }]}>
                <ThemedText type="subtitle" style={[styles.sectionTitle, { color: P.text }]}>Our Mission</ThemedText>
                <ThemedText style={[styles.sectionText, { color: P.text + '99' }]}>
                    Waste to Worth is dedicated to reducing environmental waste by helping users discover 
                    creative and practical ways to upcycle their everyday items. We believe that with a 
                    little creativity and guidance, almost anything can be transformed into something 
                    useful and beautiful.
                </ThemedText>
            </ThemedView>

            {/* Features Section */}
            <ThemedView style={[styles.section, { backgroundColor: P.card, borderRadius: Radii.md, ...(Shadows.soft as any) }]}>
                <ThemedText type="subtitle" style={[styles.sectionTitle, { color: P.text }]}>Key Features</ThemedText>
                
                <ThemedView style={styles.featureItem}>
                    <ThemedText style={[styles.featureTitle, { color: P.text }]}>📱 Smart Material Recognition</ThemedText>
                    <ThemedText style={[styles.featureText, { color: P.text + '99' }]}>
                        Use your camera to identify materials and get instant recycling suggestions.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={[styles.featureTitle, { color: P.text }]}>🎨 AI-Powered Project Ideas</ThemedText>
                    <ThemedText style={[styles.featureText, { color: P.text + '99' }]}>
                        Get personalized upcycling project ideas generated by advanced AI technology.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={[styles.featureTitle, { color: P.text }]}>📚 Step-by-Step Instructions</ThemedText>
                    <ThemedText style={[styles.featureText, { color: P.text + '99' }]}>
                        Follow detailed, easy-to-understand instructions for every project.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={[styles.featureTitle, { color: P.text }]}>📊 Progress Tracking</ThemedText>
                    <ThemedText style={[styles.featureText, { color: P.text + '99' }]}>
                        Track your recycling journey and see the positive impact you're making.
                    </ThemedText>
                </ThemedView>

                <ThemedView style={styles.featureItem}>
                    <ThemedText style={[styles.featureTitle, { color: P.text }]}>👥 Community Sharing</ThemedText>
                    <ThemedText style={[styles.featureText, { color: P.text + '99' }]}>
                        Share your creations and get inspired by others in the community.
                    </ThemedText>
                </ThemedView>
            </ThemedView>

            {/* Technology Section */}
            <ThemedView style={[styles.section, { backgroundColor: P.card, borderRadius: Radii.md, ...(Shadows.soft as any) }]}>
                <ThemedText type="subtitle" style={[styles.sectionTitle, { color: P.text }]}>Technology</ThemedText>
                <ThemedText style={[styles.sectionText, { color: P.text + '99' }]}>
                    Waste to Worth is powered by cutting-edge technology including:
                </ThemedText>
                
                <ThemedView style={styles.techItem}>
                    <ThemedText style={[styles.techTitle, { color: P.text }]}>• Google Gemini AI</ThemedText>
                    <ThemedText style={[styles.techText, { color: P.text + '99' }]}>For intelligent project generation and material analysis</ThemedText>
                </ThemedView>

                <ThemedView style={styles.techItem}>
                    <ThemedText style={[styles.techTitle, { color: P.text }]}>• Firebase</ThemedText>
                    <ThemedText style={[styles.techText, { color: P.text + '99' }]}>For secure data storage and real-time synchronization</ThemedText>
                </ThemedView>

                <ThemedView style={styles.techItem}>
                    <ThemedText style={[styles.techTitle, { color: P.text }]}>• React Native & Expo</ThemedText>
                    <ThemedText style={[styles.techText, { color: P.text + '99' }]}>For cross-platform mobile app development</ThemedText>
                </ThemedView>

                <ThemedView style={styles.techItem}>
                    <ThemedText style={[styles.techTitle, { color: P.text }]}>• Flask Backend</ThemedText>
                    <ThemedText style={[styles.techText, { color: P.text + '99' }]}>For robust API services and data processing</ThemedText>
                </ThemedView>
            </ThemedView>

            {/* Impact Section */}
            <ThemedView style={[styles.section, { backgroundColor: P.card, borderRadius: Radii.md, ...(Shadows.soft as any) }]}>
                <ThemedText type="subtitle" style={[styles.sectionTitle, { color: P.text }]}>Environmental Impact</ThemedText>
                <ThemedText style={[styles.sectionText, { color: P.text + '99' }]}>
                    Every upcycling project you complete helps reduce waste and contributes to a more 
                    sustainable future. Together, we can make a significant difference in protecting 
                    our planet for future generations.
                </ThemedText>
            </ThemedView>

            {/* Contact Section */}
            <ThemedView style={[styles.section, { backgroundColor: P.card, borderRadius: Radii.md, ...(Shadows.soft as any) }]}>
                <ThemedText type="subtitle" style={[styles.sectionTitle, { color: P.text }]}>Get in Touch</ThemedText>
                <ThemedText style={[styles.sectionText, { color: P.text + '99' }]}>
                    Have questions, suggestions, or want to share your success stories? We'd love to hear from you!
                </ThemedText>
                
                <TouchableOpacity style={[styles.contactButton, { backgroundColor: P.primary, borderRadius: Radii.lg }]} onPress={handleContactPress}>
                    <ThemedText style={styles.contactButtonText}>📧 Contact Support</ThemedText>
                </TouchableOpacity>

            </ThemedView>

            {/* Footer */}
            <ThemedView style={[styles.footerSection, { backgroundColor: P.card, borderRadius: Radii.md }]}>
                <ThemedText style={[styles.footerText, { color: P.text + '99' }]}>
                    © 2025 Waste to Worth. All rights reserved.
                </ThemedText>
                <ThemedText style={[styles.footerText, { color: P.text + '99' }]}>
                    Made with ❤️ for a sustainable future
                </ThemedText>
            </ThemedView>
        </ScrollView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    backButtonContainer: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 8,
    },
    backButton: {
        alignSelf: 'flex-start',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderWidth: 1,
    },
    backButtonText: {
        color: '#007AFF',
        fontSize: 16,
        fontWeight: '500',
    },
    headerSection: {
        padding: 24,
        marginHorizontal: 16,
        marginBottom: 16,
        alignItems: 'center',
    },
    appTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    tagline: {
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 8,
        fontStyle: 'italic',
    },
    version: {
        fontSize: 14,
        fontWeight: '500',
    },
    section: {
        padding: 20,
        marginHorizontal: 16,
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 16,
    },
    sectionText: {
        fontSize: 16,
        lineHeight: 24,
        marginBottom: 16,
    },
    featureItem: {
        marginBottom: 16,
        paddingBottom: 16,
        borderBottomWidth: 1,
    },
    featureTitle: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 8,
    },
    featureText: {
        fontSize: 14,
        lineHeight: 20,
    },
    techItem: {
        marginBottom: 12,
    },
    techTitle: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 4,
    },
    techText: {
        fontSize: 14,
        lineHeight: 20,
        marginLeft: 16,
    },
    contactButton: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        marginBottom: 12,
        alignItems: 'center',
    },
    contactButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    websiteButton: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
    },
    websiteButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    footerSection: {
        padding: 20,
        marginHorizontal: 16,
        marginBottom: 32,
        borderRadius: 12,
        alignItems: 'center',
    },
    footerText: {
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 4,
    },
});
